# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: spllbk
email: psi@spllbk.com
description: >- # this means to ignore newlines until "baseurl:"
  Psibat's blog
baseurl: ""
url: "http://spllbk.com/"
twitter_username: psibat
github_username:  psibat

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
